### PR TITLE
Saml sso

### PR DESCRIPTION
**Pull request by Jooho**
@timothyh Thanks for the catch.

I though I delete all client info but I had missed. I believe there were client name on 3 different lines in xml file and I remove it.

Please take a look at it one more time.
Thanks,
Jooho

### CODE REVIEW

**Comment by JaredBurck** [comment]
@Jooho could you please add a link "Set up SSO for multiple OCP clusters" to the `playbooks/operationalizing/index.adoc` page linking to your saml sso doc?  This will make it easier to review and publish the guide. thanks!

**Comment by Jooho** [comment]
@JaredBurck I add the link to index.adoc.

Please review it.

**Comment by Jooho** [comment]
@JaredBurck I think there should be saml_sso.html under the folder but build fail....could you take a look at it? From my side, it should work..

**Comment by JaredBurck** [comment]
thanks for updating this @Jooho.  I will look into this and will update you with what I find.

**Comment by sabre1041** [comment]
@Jooho your document must contain a valid asciidoc header otherwise it will not be compiled and converted into html.

Would you be able to add the header?

**Comment by etsauer** [comment]
@Jooho could you make the updates requested by @sabre1041 above?

**Comment by etsauer** [comment]
@Jooho any updates?

**Comment by etsauer** [comment]
Closing, as it appears to have gone stale. Please open a new PR if this contribution is still relevant.

**Pull request closed without merging**
