### PR TITLE
Updated installation guide to change references to *.cloudapps to *.apps

### PR DESCRIPTION
**Pull request by beelandc**
#### What is this PR About?
Changed *.cloudapps to *.apps in install guide 

#### How should we test or review this PR?
Confirm that all references to the **_cloudapps_** subdomain have been updated to **_apps_**

#### Is there a relevant Trello card or Github issue open for this?
#152 

#### Who would you like to review this?
cc: @redhat-cop/cant-contain-this

### CODE REVIEW

**Comment by sabre1041** [comment]
@beelandc recent merges have caused conflicts in this PR. Would you be able to review?

**Comment by beelandc** [comment]
Reviewed and resolved merge conflicts

**Comment by etsauer** [comment]
@beelandc this is still showing merge conflicts

**Comment by beelandc** [comment]
Looks like the PR sat long enough that my changes are OBE. There must have been an analogous update that got merged in previously. Not sure if we even need this any more since the only change this makes now is to remove a line

**Comment by etsauer** [comment]
@beelandc hmm, yeah I thought you fixed this in another PR. anyway, i'll close.

**Pull request closed without merging**
