### PR TITLE
Several broken link fixes

### PR DESCRIPTION
**Pull request by etsauer**
#### What is this PR About?
See above

#### How should we test or review this PR?
Eye test.

#### Who would you like to review this?
cc: @redhat-cop/cant-contain-this

### CODE REVIEW

**Comment by etsauer** [comment]
@redhat-cop/cant-contain-this-mergers ?

**Comment by rdebeasi** [comment]
In general, this looks good to me as well. It's great that htmlproofer can stop the build if we accidentally add broken links in the future.

It's worth noting that there a few cases in which the build could break without us touching any code. This could happen if we link to an external site that:

- Experiences downtime
- Moves a page, breaking a once-accurate link
- Flags our link checker as a bot and blocks it

If possible, I'd prefer to pull out htmlproofer for now. Later, it could be added as a step that that generates a warning without breaking the build, or as a tool that would be run when reviewing pull requests.

Thoughts?

**Comment by etsauer** [comment]
@rdebeasi i specifically added htmlproofer because i want to find out about broken links before i open a PR (faster feedback). If we want, we can simply remove the `set -e` so that the build doesn't exit if htmlproofer fails. thoughts?

**Comment by rdebeasi** [comment]
I took a closer look at that script and realized that it only runs locally, not in OpenShift. In that case, I don't think the issues that I brought up are worth worrying about. Sorry about that!

**Pull request merged**
